# Site settings
title: Be bold, Be you
description: Hello VeggieWorld!
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: 'https://YEJI315.github.io/'

# User settings
username: Veggie
user_description: Hello World!
user_title: Growing Developer
email: kimyeji315@gmail.com
github_username:  Veggie

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
